# MLHyperparameterTuning  Pipeline
#
# A Github Service Connection must also be created with the name "AIArchitecturesAndPractices-GitHub"

resources:
  repositories:
    - repository: aitemplates
      type: github
      name: microsoft/AI
      endpoint: AIArchitecturesAndPractices-GitHub

trigger: none

pr: none

stages:
- template: .ci/stages/deploy_notebooks_stages_v2.yml@aitemplates
  parameters:
    Agent: $(Agent_Name)
    jobDisplayName: ADOTrainDeployJob
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    TestPostfix: -$(Build.SourceBranchName)
    workload_vars: ../vars/ado_ml_batch_train_vars.yml
    post_cleanup: false
    flighting_release: false
    flighting_preview: false
    data_prep: $(data_prep)
    train: $(train)
    sql_server_name: $(sql_server_name)
    sql_database_name: $(sql_database_name)
    sql_username: $(sql_username)
    sql_password: $(sql_password)
    blob_datastore_name: $(blob_datastore_name)
    container_name: $(container_name)
    account_name: $(account_name)
    account_key: $(account_key)
